# Generated by Django 2.2.3 on 2022-12-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_blog_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(default=None, upload_to='thums/'),
        ),
    ]
